insert into questionariodeautoavaliacao (id, descricao) values (1, 'Auto Avaliação');
insert into grupoitemavaliacao  (id, descricao) values (1, 'Postura Profissional');
insert into grupoitemavaliacao  (id, descricao) values (2, 'Conteúdo');
insert into grupoitemavaliacao  (id, descricao) values (3, 'Metodologia / Recursos Didáticos');
insert into grupoitemavaliacao  (id, descricao) values (4, 'Avaliação');
insert into itemdeautoavaliacao (modeloquestionario_id, texto, grupo_id) values (1, '1.Pontualidade  (comparece às aulas no horário estabelecido)', 1);
insert into itemdeautoavaliacao (modeloquestionario_id, texto, grupo_id) values (1, '2.Assiduidade  (comparece às aulas regularmente)', 1);
insert into itemdeautoavaliacao (modeloquestionario_id, texto, grupo_id) values (1, '3.Demonstra postura profissional adequada  (apresentação pessoal, posicionamento em sala, linguagem, etc.)', 1);
insert into itemdeautoavaliacao (modeloquestionario_id, texto, grupo_id) values (1, '4.Apresenta algum problema de comunicação  (vícios de linguagem, dicção, etc.)', 1);

insert into questionarioavaliacaodeturma (id, descricao) values (1, 'Avaliação de Turma - teste');
insert into itemavaliacaodaturma (modeloavaliacao_id, texto) values (1, 'A Turma comparece às aulas no horário estabelecido?');
insert into itemavaliacaodaturma (modeloavaliacao_id, texto) values (1, 'A Turma comparece às aulas diariamente?');
insert into itemavaliacaodaturma (modeloavaliacao_id, texto) values (1, 'A Turma possui um bom rendimento escolar?');
insert into itemavaliacaodaturma (modeloavaliacao_id, texto) values (1, 'A Turma interessa-se e participa das aulas?');
insert into itemavaliacaodaturma (modeloavaliacao_id, texto) values (1, 'A Turma comporta-se adequadamente em sala de aula?');
insert into itemavaliacaodaturma (modeloavaliacao_id, texto) values (1, 'A Turma realiza as atividades propostas no prazo estabelecido?');
insert into usuarios (id, matricula, nome) values (1, '345', 'maria');
insert into usuarios (id, matricula, nome) values (2, '777', 'Pedro');
insert into professor (id) values (1);
insert into professor (id) values (2);
insert into semestreLetivo (id, ano, semestre) values (1, 2013, 2);
insert into bimestreletivo (id, bimestre, modeloautoavaliacao_id, modeloavaliacaodeturma_id, semestre_id) values (1, 1, 1, 1, 1);
insert into turmaSeriada (id, codigoSistemaAcademico) values (1, '23');
insert into diario (id, codigoSistemaAcademico, semestre_id, turma_id) values (1, '32', 1, 1);
insert into diario_professor (diario_id, professores_id) values (1, 1);
insert into turmaSeriada (id, codigoSistemaAcademico) values (2, '8877');
insert into diario (id, codigoSistemaAcademico, semestre_id, turma_id) values (2, '09090', 1, 2);
insert into diario_professor (diario_id, professores_id) values (2, 1);
insert into diario (id, codigoSistemaAcademico, semestre_id, turma_id) values (3, '08080', 1, 2);
insert into diario_professor (diario_id, professores_id) values (3, 2);
